### ISSUE TITLE
retrain the network but get a poor performance

### ISSUE THREAD

**Issue by MaybeOjbk** [fuy34/DFV#2]
I followed your instruction and used your processed DDFF12 and FoD5000 dataset， then ran the train.py with  stack_num 5 batchsize 20  and use_diff 1, but in the evaluation of DDFF12, I get poor results.  I did 2 experiments,  In the first experiment, I only used DDFF12 to train the network, I got 7.8e-3 in MSE. In the second experiment, I use both DDFF12 and Fod5000 to train the network, but I got 1.66e-2.  And my pytorch version is 1.8 , GPU is 2080

**Comment by fuy34** [comment]
Hi, 
Thank you for your interest in our work. Can you try the following things to make sure if the environment is correctly set up? 
1. Use our pre-trained model to test and evaluate;
2. Check if you commit this part. I put this is to ensure our pre-trained model can run appropriate 
   https://github.com/fuy34/DFV/blob/374420792ffde65bc68db101e25cdc5b6cbf0990/eval_DDFF12.py#L37-L41
3. check if your training and testing setting is identical, especially  ```--stack_num```, ```--use_diff``` and  ```--level ```

**Comment by MaybeOjbk** [comment]
I'm sorry, I didn't notice this line,  the reason why I got the poor result is that I use trained DFV model  but evaled in FV strategy which means  the model didn't use diff_feat_volume and leaded to the poor results.  But In my re-training, I find that only use DDFF-12 dataset to train DFV model can better results then using DDFF-12 and FoD500 dataset. Training in DDFF-12 dataset, I get 6.09e-4, while training in both DDFF-12 and FoD500 I get  6.54e-4.

**Comment by fuy34** [comment]
Haha, do you mean test on the DDFF-12 only? 
It could be, because if the training and test data are from the same domain, the model may get more familiar with the domain distribution, especially when the number of training/test samples is small (just as in our case > ... <).

**Comment by MaybeOjbk** [comment]
thanks

**Comment by MaybeOjbk** [comment]
But I also get a problem,  I followed your instruction in your code to train DFV model with DDFF-12 dataset, but I can't get the same result, I got 6.7e-4, while you get 5.7e-4(also you train on Fod5000 dataset). Did you retrain your model with your train.py and also got the same result  compared with your paper?  Or did you use some tricks which didn't write in your code ?

**Comment by fuy34** [comment]
Sorry for the late reply. I did not check the repo. often these days.  

What is the performance of the FV version?  I did not use any other tricks. It may be due to some package version difference or random process. Also, 6.7e-4 is not a bad number. It already beats all the other baselines I have awarded of. :)
